export const PERSONAL_INFO_NAME = 'PERSONAL_INFO_NAME';
export const PERSONAL_INFO_EMAIL = 'PERSONAL_INFO_EMAIL';
export const PERSONAL_INFO_DOB = 'PERSONAL_INFO_DOB';
export const PERSONAL_INFO_ADDRESS = 'PERSONAL_INFO_ADDRESS';