export const PERSONAL_INFO_NAME = "PERSONAL_INFO_NAME";
export const PERSONAL_INFO_EMAIL = "PERSONAL_INFO_EMAIL";
export const PERSONAL_INFO_DOB = "PERSONAL_INFO_DOB";
export const PERSONAL_INFO_ADDRESS = "PERSONAL_INFO_ADDRESS";

export const SKILLS_PROGRAMMING_LANGUAGES = "SKILLS_PROGRAMMING_LANGUAGES";
export const SKILLS_EXPERTIES = "SKILLS_EXPERTIES";
export const SKILLS_TOOLS_AND_TECHNOLOGIES = "SKILLS_TOOLS_AND_TECHNOLOGIES";
export const SKILLS_TECHNICAL_ELECTIVES = "SKILLS_TECHNICAL_ELECTIVES";

export const EDUCATION_DEGREE_NAME = "EDUCATION_DEGREE_NAME";
export const EDUCATION_INSTITUTE = "EDUCATION_INSTITUTE";
export const EDUCATION_YEAR = "EDUCATION_YEAR";
export const EDUCATION_CPI = "EDUCATION_CPI";
export const EDUCATION_ADD_DEGREE = "EDUCATION_ADD_DEGREE";

export const PROFESSIONAL_EXP_COMPANY = "PROFESSIONAL_EXP_COMPANY";
export const PROFESSIONAL_EXP_DESCRIPTION = "PROFESSIONAL_EXP_DESCRIPTION";
export const PROFESSIONAL_EXP_GUIDE = "PROFESSIONAL_EXP_GUIDE";
export const PROFESSIONAL_EXP_START = "PROFESSIONAL_EXP_START";
export const PROFESSIONAL_EXP_END = "PROFESSIONAL_EXP_END";
export const PROFESSIONAL_EXP_TEAM = "PROFESSIONAL_EXP_TEAM";

export const PROJECT_NAME = "PROJECT_NAME";
export const PROJECT_DESCRIPTION = "PROJECT_DESCRIPTION";
export const PROJECT_GUIDE = "PROJECT_GUIDE";
export const PROJECT_START = "PROJECT_START";
export const PROJECT_END = "PROJECT_END";
export const PROJECT_TEAM = "PROJECT_TEAM";

export const POSITION_RESPONSIBILITY = "POSITION_RESPONSIBILITY";

export const AWARDS_ACHIEVEMENTS = "AWARDS_ACHIEVEMENTS";
export const ADD_AWARDS_ACHIEVEMENTS = "ADD_AWARDS_ACHIEVEMENTS";

export const INTERESTS_HOBBIES = "INTERESTS_HOBBIES";
export const ADD_HOBBIES = "ADD_HOBBIES";
