export const PERSONAL_INFO_NAME = 'PERSONAL_INFO_NAME';
export const PERSONAL_INFO_EMAIL = 'PERSONAL_INFO_EMAIL';
export const PERSONAL_INFO_DOB = 'PERSONAL_INFO_DOB';
export const PERSONAL_INFO_ADDRESS = 'PERSONAL_INFO_ADDRESS';

export const SKILLS_PROGRAMMING_LANGUAGES = 'SKILLS_PROGRAMMING_LANGUAGES';
export const SKILLS_EXPERTIES = 'SKILLS_EXPERTIES';
export const SKILLS_TOOLS_AND_TECHNOLOGIES = 'SKILLS_TOOLS_AND_TECHNOLOGIES';
export const SKILLS_TECHNICAL_ELECTIVES = 'SKILLS_TECHNICAL_ELECTIVES';